# Generated by Django 5.1.5 on 2025-07-09 10:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='メールアドレス')),
                ('company_name', models.CharField(max_length=255, verbose_name='会社名')),
                ('contact_name', models.CharField(max_length=100, verbose_name='担当者名')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('rakuten_shop_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='楽天店舗ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_staff', models.BooleanField(default=False, verbose_name='スタッフ権限')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='登録日時')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_status', models.CharField(choices=[('trial', '無料トライアル'), ('active', '有効'), ('past_due', '支払い遅延'), ('canceled', 'キャンセル'), ('inactive', '無効')], default='inactive', max_length=20, verbose_name='サブスクリプション状態')),
                ('trial_end_date', models.DateTimeField(blank=True, null=True, verbose_name='トライアル終了日')),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True, verbose_name='サブスクリプション終了日')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー',
                'db_table': 'users',
            },
        ),
    ]
