# Generated by Django 5.1.5 on 2025-07-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_master',
            field=models.BooleanField(default=False, help_text='全機能・全店舗データにアクセス可能', verbose_name='マスターアカウント'),
        ),
    ]
