# Generated by Django 5.1.5 on 2025-07-18 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_auto_search_enabled_user_auto_search_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_invited_user',
            field=models.BooleanField(default=False, help_text='マスターアカウントから招待されたユーザー（ダッシュボードに表示）', verbose_name='招待ユーザー'),
        ),
    ]
