# Generated by Django 5.1.5 on 2025-07-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_invited_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='auto_search_enabled',
        ),
        migrations.AddField(
            model_name='user',
            name='auto_rpp_search_enabled',
            field=models.BooleanField(default=True, help_text='毎日深夜に自動でRPPキーワード順位を確認する', verbose_name='RPP自動検索有効'),
        ),
        migrations.AddField(
            model_name='user',
            name='auto_seo_search_enabled',
            field=models.BooleanField(default=True, help_text='毎日深夜に自動でSEOキーワード順位を確認する', verbose_name='SEO自動検索有効'),
        ),
        migrations.AlterField(
            model_name='user',
            name='auto_search_time',
            field=models.TimeField(blank=True, default='10:00', help_text='毎日自動検索を実行する時間（24時間形式・マスターアカウントのみ有効）', null=True, verbose_name='自動検索時間'),
        ),
    ]
