# Generated by Django 5.1.5 on 2025-07-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_auto_search_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_plan',
            field=models.CharField(choices=[('standard', 'スタンダードプラン'), ('master', 'マスタープラン')], default='standard', help_text='スタンダード: 2,980円/月 (SEO&RPP各30個), マスター: 4,980円/月 (SEO&RPP各100個)', max_length=20, verbose_name='サブスクリプションプラン'),
        ),
    ]
