# Generated by Django 5.1.5 on 2025-07-09 10:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='キーワード')),
                ('rakuten_shop_id', models.CharField(max_length=100, verbose_name='楽天店舗ID')),
                ('target_product_url', models.URLField(blank=True, help_text='順位を追跡したい自社商品のURL', null=True, verbose_name='対象商品URL')),
                ('target_product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='対象商品ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'キーワード',
                'verbose_name_plural': 'キーワード',
                'unique_together': {('user', 'keyword', 'rakuten_shop_id')},
            },
        ),
        migrations.CreateModel(
            name='RankingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, help_text='見つからない場合はNULL', null=True, verbose_name='順位')),
                ('total_results', models.IntegerField(default=0, verbose_name='総検索結果数')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='チェック日時')),
                ('is_found', models.BooleanField(default=False, verbose_name='発見')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_results', to='seo_ranking.keyword', verbose_name='キーワード')),
            ],
            options={
                'verbose_name': '順位結果',
                'verbose_name_plural': '順位結果',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='検索キーワード')),
                ('execution_time', models.FloatField(default=0, verbose_name='実行時間（秒）')),
                ('pages_checked', models.IntegerField(default=0, verbose_name='チェックページ数')),
                ('products_found', models.IntegerField(default=0, verbose_name='発見商品数')),
                ('success', models.BooleanField(default=True, verbose_name='成功')),
                ('error_details', models.TextField(blank=True, null=True, verbose_name='エラー詳細')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '検索ログ',
                'verbose_name_plural': '検索ログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TopProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='順位')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名')),
                ('product_url', models.URLField(verbose_name='商品URL')),
                ('product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品ID')),
                ('shop_name', models.CharField(max_length=255, verbose_name='店舗名')),
                ('shop_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='店舗ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格')),
                ('review_count', models.IntegerField(default=0, verbose_name='レビュー数')),
                ('review_average', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='レビュー平均')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='商品画像URL')),
                ('is_own_product', models.BooleanField(default=False, verbose_name='自社商品')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='収集日時')),
                ('ranking_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_products', to='seo_ranking.rankingresult', verbose_name='順位結果')),
            ],
            options={
                'verbose_name': '上位商品',
                'verbose_name_plural': '上位商品',
                'ordering': ['rank'],
                'unique_together': {('ranking_result', 'rank')},
            },
        ),
    ]
