# Generated by Django 5.1.5 on 2025-07-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topproduct',
            name='catchcopy',
            field=models.TextField(blank=True, null=True, verbose_name='キャッチコピー'),
        ),
        migrations.AddField(
            model_name='topproduct',
            name='genre_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ジャンルID'),
        ),
        migrations.AddField(
            model_name='topproduct',
            name='point_rate',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='ポイント倍率'),
        ),
        migrations.AddField(
            model_name='topproduct',
            name='product_spec',
            field=models.TextField(blank=True, null=True, verbose_name='製品情報・商品仕様'),
        ),
        migrations.AddField(
            model_name='topproduct',
            name='tag_ids',
            field=models.TextField(blank=True, help_text='複数のタグIDをJSON配列で保存', null=True, verbose_name='タグID（JSON形式）'),
        ),
    ]
