# Generated by Django 5.1.5 on 2025-07-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ranking', '0002_topproduct_catchcopy_topproduct_genre_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topproduct',
            name='genre_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ジャンル名'),
        ),
        migrations.AddField(
            model_name='topproduct',
            name='tag_names',
            field=models.TextField(blank=True, help_text='複数のタグ名をJSON配列で保存', null=True, verbose_name='タグ名（JSON形式）'),
        ),
    ]
