# Generated by Django 5.1.5 on 2025-07-12 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ranking', '0003_topproduct_genre_name_topproduct_tag_names'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RPPKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='検索キーワード')),
                ('rakuten_shop_id', models.CharField(max_length=100, verbose_name='楽天店舗ID')),
                ('target_product_url', models.URLField(blank=True, help_text='追跡したい自社商品のURL', null=True, verbose_name='対象商品URL')),
                ('target_product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='対象商品ID')),
                ('is_active', models.BooleanField(default=True, help_text='自動実行の対象にするか', verbose_name='有効')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpp_keywords', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'RPPキーワード',
                'verbose_name_plural': 'RPPキーワード',
                'unique_together': {('user', 'keyword', 'rakuten_shop_id')},
            },
        ),
        migrations.CreateModel(
            name='RPPResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(blank=True, help_text='見つからない場合はNULL', null=True, verbose_name='広告順位')),
                ('total_ads', models.IntegerField(default=0, help_text='検索結果で見つかった広告の総数', verbose_name='総広告数')),
                ('pages_checked', models.IntegerField(default=1, help_text='何ページまでチェックしたか', verbose_name='チェックページ数')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='チェック日時')),
                ('is_found', models.BooleanField(default=False, verbose_name='発見')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpp_results', to='seo_ranking.rppkeyword', verbose_name='キーワード')),
            ],
            options={
                'verbose_name': 'RPP結果',
                'verbose_name_plural': 'RPP結果',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='RPPSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255, verbose_name='検索キーワード')),
                ('execution_time', models.FloatField(default=0, verbose_name='実行時間（秒）')),
                ('pages_checked', models.IntegerField(default=0, verbose_name='チェックページ数')),
                ('ads_found', models.IntegerField(default=0, verbose_name='発見広告数')),
                ('success', models.BooleanField(default=True, verbose_name='成功')),
                ('error_details', models.TextField(blank=True, null=True, verbose_name='エラー詳細')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpp_search_logs', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'RPP検索ログ',
                'verbose_name_plural': 'RPP検索ログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RPPAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='1位, 2位, 3位...', verbose_name='広告順位')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名')),
                ('catchcopy', models.TextField(blank=True, null=True, verbose_name='キャッチコピー')),
                ('product_url', models.URLField(verbose_name='商品URL')),
                ('product_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品ID')),
                ('shop_name', models.CharField(max_length=255, verbose_name='店舗名')),
                ('shop_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='店舗ID')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='価格')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='商品画像URL')),
                ('bid_amount', models.IntegerField(blank=True, help_text='円単位（推定値）', null=True, verbose_name='推定入札単価')),
                ('position_on_page', models.IntegerField(default=1, help_text='そのページの何番目の広告か', verbose_name='ページ内位置')),
                ('page_number', models.IntegerField(default=1, help_text='何ページ目に表示されているか', verbose_name='ページ番号')),
                ('is_own_product', models.BooleanField(default=False, verbose_name='自社商品')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='収集日時')),
                ('rpp_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpp_ads', to='seo_ranking.rppresult', verbose_name='RPP結果')),
            ],
            options={
                'verbose_name': 'RPP広告',
                'verbose_name_plural': 'RPP広告',
                'ordering': ['rank'],
                'unique_together': {('rpp_result', 'rank')},
            },
        ),
    ]
