# Generated by Django 5.1.5 on 2025-07-12 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ranking', '0004_rppkeyword_rppresult_rppsearchlog_rppad'),
    ]

    operations = [
        migrations.AddField(
            model_name='rppresult',
            name='memo',
            field=models.TextField(blank=True, help_text='CPC変更履歴、改善履歴などを記録', null=True, verbose_name='メモ'),
        ),
    ]
