# Generated by Django 5.1.5 on 2025-07-12 06:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ranking', '0005_rppresult_memo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RPPBulkSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='実行日時')),
                ('keywords_count', models.IntegerField(default=0, verbose_name='実行キーワード数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功件数')),
                ('error_count', models.IntegerField(default=0, verbose_name='エラー件数')),
                ('total_execution_time', models.FloatField(default=0, verbose_name='総実行時間（秒）')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rpp_bulk_search_logs', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'RPP一括検索ログ',
                'verbose_name_plural': 'RPP一括検索ログ',
                'ordering': ['-executed_at'],
            },
        ),
    ]
