# Generated by Django 5.1.5 on 2025-07-12 06:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ranking', '0006_rppbulksearchlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRankingCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='実行日時')),
                ('targets_count', models.IntegerField(default=0, verbose_name='対象店舗数')),
                ('checks_executed', models.IntegerField(default=0, verbose_name='実行チェック数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功件数')),
                ('error_count', models.IntegerField(default=0, verbose_name='エラー件数')),
                ('total_ranked_items', models.IntegerField(default=0, verbose_name='総ランクイン商品数')),
                ('total_execution_time', models.FloatField(default=0, verbose_name='総実行時間（秒）')),
                ('is_completed', models.BooleanField(default=False, verbose_name='完了')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_ranking_checks', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '日次ランキングチェック',
                'verbose_name_plural': '日次ランキングチェック',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='RankingTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_code', models.CharField(help_text='楽天の店舗ID（URL内のコード）', max_length=100, verbose_name='店舗コード')),
                ('shop_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='店舗名')),
                ('target_product_codes', models.TextField(blank=True, help_text='調査対象の商品コード（複数の場合は改行区切り）', null=True, verbose_name='対象商品コード')),
                ('target_genre_ids', models.TextField(blank=True, help_text='調査するジャンルID（複数の場合は改行区切り）', null=True, verbose_name='調査対象ジャンルID')),
                ('check_total_ranking', models.BooleanField(default=True, help_text='楽天総合ランキングをチェックするか', verbose_name='総合ランキングチェック')),
                ('is_active', models.BooleanField(default=True, help_text='自動チェックの対象にするか', verbose_name='有効')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_targets', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'ランキング調査対象',
                'verbose_name_plural': 'ランキング調査対象',
                'unique_together': {('user', 'shop_code')},
            },
        ),
        migrations.CreateModel(
            name='RankingCheckLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('total', '総合ランキング'), ('genre', 'ジャンル別ランキング')], max_length=50, verbose_name='チェック種別')),
                ('genre_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='ジャンルID')),
                ('genre_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ジャンル名')),
                ('checked_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='チェック日時')),
                ('total_items_checked', models.IntegerField(default=0, verbose_name='チェックした商品数')),
                ('ranked_items_found', models.IntegerField(default=0, verbose_name='ランクイン商品数')),
                ('success', models.BooleanField(default=True, verbose_name='成功')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('execution_time', models.FloatField(default=0, verbose_name='実行時間（秒）')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking_check_logs', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_logs', to='seo_ranking.rankingtarget', verbose_name='調査対象')),
            ],
            options={
                'verbose_name': 'ランキングチェックログ',
                'verbose_name_plural': 'ランキングチェックログ',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='RakutenRankingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(help_text='ランキング順位（1位、2位...）', verbose_name='順位')),
                ('product_name', models.CharField(max_length=255, verbose_name='商品名')),
                ('product_code', models.CharField(max_length=100, verbose_name='商品コード')),
                ('shop_code', models.CharField(max_length=100, verbose_name='店舗コード')),
                ('shop_name', models.CharField(max_length=255, verbose_name='店舗名')),
                ('product_url', models.URLField(verbose_name='商品URL')),
                ('product_price', models.IntegerField(blank=True, null=True, verbose_name='商品価格')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='商品画像URL')),
                ('is_own_product', models.BooleanField(default=False, help_text='調査対象店舗の商品かどうか', verbose_name='自店舗商品')),
                ('review_count', models.IntegerField(default=0, verbose_name='レビュー数')),
                ('review_average', models.FloatField(default=0.0, verbose_name='レビュー平均')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='収集日時')),
                ('check_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='seo_ranking.rankingchecklog', verbose_name='チェックログ')),
            ],
            options={
                'verbose_name': 'ランキング結果',
                'verbose_name_plural': 'ランキング結果',
                'ordering': ['rank'],
                'unique_together': {('check_log', 'rank')},
            },
        ),
    ]
