# Generated by Django 5.1.5 on 2025-07-12 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ranking', '0007_dailyrankingcheck_rankingtarget_rankingchecklog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RakutenGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id', models.IntegerField(db_index=True, unique=True, verbose_name='ジャンルID')),
                ('genre_name', models.CharField(max_length=255, verbose_name='ジャンル名')),
                ('genre_level', models.IntegerField(db_index=True, help_text='0=ルート, 1=第1階層, ..., 5=第5階層', verbose_name='ジャンル階層')),
                ('parent_genre_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='親ジャンルID')),
                ('genre_path', models.TextField(blank=True, help_text='ルートからのパス（例: /100283/100284/100285）', verbose_name='ジャンルパス')),
                ('is_active', models.BooleanField(default=True, help_text='ランキング調査対象にするかどうか', verbose_name='有効フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '楽天ジャンルマスター',
                'verbose_name_plural': '楽天ジャンルマスター',
                'db_table': 'rakuten_genre_master',
                'ordering': ['genre_level', 'genre_id'],
                'indexes': [models.Index(fields=['genre_level', 'is_active'], name='rakuten_gen_genre_l_d05a3b_idx')],
            },
        ),
    ]
