# Generated by Django 5.1.5 on 2025-07-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ranking', '0009_rankingtarget_check_all_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingtarget',
            name='target_level1_genre_ids',
            field=models.TextField(blank=True, help_text='調査対象の第1階層ジャンルID（改行区切り）', null=True, verbose_name='対象第1階層ジャンルID'),
        ),
        migrations.AlterField(
            model_name='rankingtarget',
            name='check_all_genres',
            field=models.BooleanField(default=False, help_text='第5階層までの全ジャンルをチェックするか', verbose_name='全ジャンルチェック'),
        ),
    ]
