# Generated by Django 5.1.5 on 2025-07-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ranking', '0010_rankingtarget_target_level1_genre_ids_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyrankingcheck',
            name='user',
        ),
        migrations.DeleteModel(
            name='RakutenGenre',
        ),
        migrations.AlterUniqueTogether(
            name='rakutenrankingresult',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rakutenrankingresult',
            name='check_log',
        ),
        migrations.RemoveField(
            model_name='rankingchecklog',
            name='target',
        ),
        migrations.RemoveField(
            model_name='rankingchecklog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='rankingtarget',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rankingtarget',
            name='user',
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='memo',
            field=models.TextField(blank=True, help_text='分析結果や気づいたことを記録', null=True, verbose_name='メモ'),
        ),
        migrations.DeleteModel(
            name='DailyRankingCheck',
        ),
        migrations.DeleteModel(
            name='RakutenRankingResult',
        ),
        migrations.DeleteModel(
            name='RankingCheckLog',
        ),
        migrations.DeleteModel(
            name='RankingTarget',
        ),
    ]
