# Generated by Django 5.1.5 on 2025-07-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ranking', '0011_remove_dailyrankingcheck_user_delete_rakutengenre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingresult',
            name='found_product_url',
            field=models.URLField(blank=True, help_text='見つかった商品のURL', null=True, verbose_name='発見商品URL'),
        ),
        migrations.AddField(
            model_name='rankingresult',
            name='total_products',
            field=models.IntegerField(blank=True, help_text='検索結果の総商品数', null=True, verbose_name='総商品数'),
        ),
    ]
