# Generated by Django 5.1.5 on 2025-07-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo_ranking', '0012_rankingresult_found_product_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rankingresult',
            name='ai_analysis',
            field=models.TextField(blank=True, help_text='AIによる競合分析結果', null=True, verbose_name='AI分析結果'),
        ),
    ]
